apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globaloptima
  template:
    metadata:
      labels:
        app: globaloptima
    spec:
      containers:
        - image: mzakel/globaloptima-customer:2022-11-30-13-40-42
          name: globaloptima-customer
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://dumbo.db.elephantsql.com:5432/ffksrvhb
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: ffksrvhb
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: password
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: globaloptima
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: globaloptima
